config/routes.rb
ProjectApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :testimonials

  resources :services do
    resources :projects 
  end

  root to: 'static_pages#home'

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/testimonials', to: 'testimonials#index'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  

end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Service < ActiveRecord::Base
  attr_accessible :description, :name

  has_many :projects, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true 
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  load_and_authorize_resource

  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end
 
  def new
    @service = Service.new
  end

  def edit
    @service = Service.find(params[:id])
  end

  def create
    @service = Service.new(params[:service])
      if @service.save
        flash[:success] = "Service was created!"
        redirect_to @service
      else
        render 'new'
      end
  end

  def update
    @service = Service.find(params[:id])

      if @service.update_attributes(params[:service])
        flash[:success] = "Service was updated!"
        redirect_to @service
      else
        render 'edit'
      end
  
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    flash[:notice] = "Service was removed."
    redirect_to services_url
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@service.errors.count, "error") %> 
      </div>
      <ul>
      <% @service.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-medium btn-primary" %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
<% if current_user != nil && is_admin? %>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span12">
        <h1>Services</h1>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span3">
        <h2>Name</h2>
      </div>
      <div class="span6">
        <h2>Description</h2>
      </div>
      <div class="span3">
        <h2>Manage</h2>
      </div>
    </div>
    <% @services.each do |service| %>
    <div class="row-fluid bottom-spacer">
      <div class="span3 center">
          <%= service.name %> 
      </div>
      <div class="span6 center">
          <%= service.description %>
      </div>
      <div class="span3 center">
          <%= link_to 'Show', service %>
          <%= link_to 'Edit', edit_service_path(service) %>
          <%= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      </div> 
      <%end%>
    <br />
    <div class="row-fluid">
      <%= link_to 'New Service', new_service_path %>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row-fluid">
        <h1>Services</h1>
    </div>
    <% @services.each do |service| %>
    <div class="row-fluid">
      <div class="span12 top-spacer">
        <div class="span3">
          <h2><%= service.name %></h2>
        </div>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span9 offset1">
        <%= service.description %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span9 offset1">
        <%= link_to 'Check out our projects', service %>
      </div>
    </div>
    <% end %>
  </div>
<%end%>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<div class="container">
	<div class="row-fluid">
		<div class="span12 center">
			<h1><%= @service.name %></h1>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12 center">
			<%= @service.description %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span12 center">
			<h2>Projects </h2>
			<% @selected = Project.all %>
			<% @selected.each do |project| %>
				<% if (project.service_id == @service.id) %>
					<div class="row-fluid">
						<div class="span2 offset5 center">
						<%= link_to project.name, service_project_path(@service.id,project) %>
					</div>
					</div>
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span3">
			<% if current_user != nil && is_admin? %>
			<%= link_to 'Add Project', new_service_project_path(@service) %> |
			<%= link_to 'Edit Service', edit_service_path(@service) %> |
			<% end %>
			<%= link_to 'Back', services_path %>
		</div>
	</div>
</div>