config/routes.rb
ProjectApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :testimonials

  resources :services do
    resources :projects 
  end

  root to: 'static_pages#home'

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/testimonials', to: 'testimonials#index'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  service_id  :integer
#  start_date  :date
#  end_date    :date
#

class Project < ActiveRecord::Base
  attr_accessible :start_date, :end_date, :description, :name

  belongs_to :service
  has_many :testimonials

  validates :name, presence: true
  validates :description, presence: true
  validates :start_date, presence: true, :unless => :start_must_be_before_end_date
  validates :end_date, presence: true, :unless => :end_must_be_after_start_date
  
  private
  def start_must_be_before_end_date
    errors.add(:start_date, "must be before end date") if
       self.start_date > self.end_date
  end 

  def end_must_be_after_start_date
  	errors.add(:end_date, "must be after start date") if 
  		self.end_date < self.start_date
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :get_service
  load_and_authorize_resource
 
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = @service.projects.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = @service.projects.build(params[:project])
    if @project.save
      flash[:success] = "Project was created!"
      redirect_to service_path(@service)
    else
     render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:success] = "Project was updated!"
      redirect_to service_project_path(@service,@project)
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project was removed"
    redirect_to service_path(@service)
  end

  def get_service
    @service = Service.find(params[:service_id])
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for( [@service,@project] ) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-error">
        The form contains <%= pluralize(@project.errors.count, "error") %> 
      </div>
      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date, :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date, :order => [:month, :day, :year] %>
  </div>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-medium btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Back', service_project_path(@project.service_id, @project) %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/projects/show.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <h2><%= @project.name %> | <%= @project.description %></h2>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12 center">
      <%= @project.start_date.strftime('%m/%d/%Y') %> to <%= @project.end_date.strftime('%m/%d/%Y') %>
    </div>
  </div>
  <div class="row=fluid">
      <div class="span11 center">
          <%= Service.find(@project.service_id).name %>
      </div>
  </div>
  <div class="row-fluid">
    <% if current_user != nil && is_admin? %>
    <%= link_to 'Edit', edit_service_project_path(@project.service_id, @project) %> |
    <%= link_to 'Delete', service_project_path(@service), method: :delete, data: { confirm: 'Are you sure?' } %> |
    <% end %>
    <%= link_to 'Back', service_path(@project.service_id) %>
  </div>
</div>