config/routes.rb
ProjectApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :testimonials

  resources :services do
    resources :projects 
  end

  root to: 'static_pages#home'

  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/testimonials', to: 'testimonials#index'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
  attr_accessible :comment, :name, :project_id
  belongs_to :project
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  # GET /testimonials
  # GET /testimonials.json
  def index
    @testimonials = Testimonial.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testimonials }
    end
  end

  # GET /testimonials/1
  # GET /testimonials/1.json
  def show
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/new
  # GET /testimonials/new.json
  def new
    @testimonial = Testimonial.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testimonial }
    end
  end

  # GET /testimonials/1/edit
  def edit
    @testimonial = Testimonial.find(params[:id])
  end

  # POST /testimonials
  # POST /testimonials.json
  def create
    @testimonial = Testimonial.new(params[:testimonial])

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully created.' }
        format.json { render json: @testimonial, status: :created, location: @testimonial }
      else
        format.html { render action: "new" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testimonials/1
  # PUT /testimonials/1.json
  def update
    @testimonial = Testimonial.find(params[:id])

    respond_to do |format|
      if @testimonial.update_attributes(params[:testimonial])
        format.html { redirect_to @testimonial, notice: 'Testimonial was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1
  # DELETE /testimonials/1.json
  def destroy
    @testimonial = Testimonial.find(params[:id])
    @testimonial.destroy

    respond_to do |format|
      format.html { redirect_to testimonials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= form_for(@testimonial) do |f| %>
  <% if @testimonial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimonial.errors.count, "error") %> prohibited this testimonial from being saved:</h2>

      <ul>
      <% @testimonial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :service_id %><br />
    <%= f.select :service_id, options_from_collection_for_select(Service.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/testimonials/edit.html.erb
<h1>Editing testimonial</h1>

<%= render 'form' %>

<%= link_to 'Show', @testimonial %> |
<%= link_to 'Back', testimonials_path %>

app/views/testimonials/index.html.erb
<div class="container">
  <div class="row-fluid">
    <h1>Listing testimonials</h1>
  </div>
  <div class="row-fluid">
    <div class="span3">
      <h2>Comment</h2>
    </div>
    <div class="span3">
      <h2>Name</h2>
    </div>
    <div class="span3">
      <h2>Service</h2>
    </div>
    <div class="span3">
      <h2>Manage</h2>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span3 center">
      <% @testimonials.each do |testimonial| %>
      <%= testimonial.comment %>
      <% end %>
    </div>
    <div class="span3 center">
      <% @testimonials.each do |testimonial| %>
      <%= testimonial.name %>
      <% end %>
    </div>
    <div class="span3 center">
      <% @testimonials.each do |testimonial| %>
      <%= Service.find(testimonial.service_id).name %>
      <% end %>
    </div>
    <div class="span3 center">
      <% @testimonials.each do |testimonial| %>
      <%= link_to 'Show', testimonial %>
      <%= link_to 'Edit', edit_testimonial_path(testimonial) %>
      <%= link_to 'Destroy', testimonial, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
  <br />
  <%= link_to 'New Testimonial', new_testimonial_path %>
</div>

app/views/testimonials/new.html.erb
<h1>New testimonial</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonials_path %>

app/views/testimonials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @testimonial.comment %>
</p>

<p>
  <b>Name:</b>
  <%= @testimonial.name %>
</p>

<p>
  <b>Service:</b>
  <%= @testimonial.service_id %>
</p>


<%= link_to 'Edit', edit_testimonial_path(@testimonial) %> |
<%= link_to 'Back', testimonials_path %>